---
title: "Spin-within combination model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(ggthemes)
library(jsonlite)
library(readxl)
library(tidyboot)
#library(GGally)
library(coda)
library(data.table)
library(ggpubr)
library(ggridges)



estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}

```


```{r}
flip <- function(x){
  coin <- sample(c(0,1), size = 1, replace = TRUE, prob = c(1 - x,x))
  return(coin)
}

```

# Data

```{r}
data <- read_csv("../data/merged_data.csv")

```

# Samples

```{r}
model <- bind_rows(
  fread("../model/output/spin-within_model_slope_variance_prediction-25000_burn200000_lag9_chain1.csv"),
  fread("../model/output/spin-within_model_slope_variance_prediction-25000_burn200000_lag9_chain2.csv"),
  fread("../model/output/spin-within_model_slope_variance_prediction-25000_burn200000_lag9_chain3.csv"),
  fread("../model/output/spin-within_model_slope_variance_prediction-25000_burn200000_lag9_chain4.csv")
)

#model <- readRDS("../model/output/comb_model.rds")

model_predictions <- model %>%filter(a == "prediction")%>%saveRDS("../model/output/comb_model_predictions.rds")

model <- model %>% filter(a != "prediction")%>%saveRDS("../model/output/comb_model_parameters.rds")
```


```{r}
model_predictions <- readRDS("../model/output/comb_model_predictions.rds")

model <- readRDS("../model/output/comb_model_parameters.rds")
```

# Model predictions

## Combination prediction

```{r}
prediction <- model_predictions %>%
  select(-a, -g)%>%
  rename(model = b,
         condition = c,
         familiar = d, 
         subid = e,
         pred = f)%>%
  group_by(model)%>%sample_n(1000)

prediction%>%left_join(data %>% select(condition,familiar,subid,subage, correct))%>%
  rowwise()%>%
  mutate(bin_pred = flip(pred),
         match = ifelse(bin_pred == correct, 1, 0))%>%
  group_by(model, subage)%>%
  summarise(match = mean(match, na.rm = T))
  
```

### comparison to chance

```{r}
mpred <- model_predictions%>%
  select(-a, -g)%>%
  rename(model = b,
         condition = c,
         familiar = d,
         subid = e,
         pred = f)%>%
  group_by(model, condition,familiar,subid)%>%
  summarise(model_mean = estimate_mode(pred),
            model_ci_lower = hdi_lower(pred),
            model_ci_upper = hdi_upper(pred))


chance_id <- mpred%>%
  left_join(data %>% select(condition,subage,familiar,subid, correct))%>%
  filter(!is.na(subage))%>%
  #ungroup()%>%
  rowwise()%>%
  mutate(pred = flip(model_mean))%>%
  ungroup()%>%
  mutate(#match = ifelse(round(model_mean) == correct, 1, 0),
         match = ifelse(pred == correct, 1, 0))%>%
  group_by(subid, subage,model)%>%
  summarise(mean = mean(match, na.rm = T))

chance <- mpred%>%
  left_join(data %>% select(condition,subage,familiar,subid, correct))%>%
  filter(!is.na(subage))%>%
  #ungroup()%>%
  rowwise()%>%
  mutate(pred = flip(model_mean))%>%
  ungroup()%>%
  mutate(#match = ifelse(round(model_mean) == correct, 1, 0),
         match = ifelse(pred == correct, 1, 0))%>%
  group_by(subage,model)%>%
  tidyboot_mean(col = match, na.rm = T)


ggplot(chance, aes(x = model, y = mean))+
  geom_hline(yintercept = 0.5, lty = 2, alpha = .5)+
  geom_dotplot(data = chance_id, binaxis='y', stackdir='center',
               stackratio=1.5, dotsize=.5, alpha = .2)+
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper, col = model), size = 0.6)+
  ylim(0,1)+
  facet_grid(~subage)+
  labs(x = "Model", y = "Proportion Correct Predictions")+
  scale_color_ptol()+
  scale_fill_ptol()+
  guides(col = F)+
  theme_minimal()
```

```{r}
mpred%>%
  left_join(data %>% select(condition,subage,familiar,subid, correct))%>%
  filter(!is.na(subage))%>%
  rowwise()%>%
  mutate(pred = flip(model_mean))%>%
  ungroup()%>%
  group_by(model, correct, pred)%>%
  filter(!is.na(correct))%>%
  summarise(n= n())%>%
  group_by(model,correct)%>%
  mutate(prop = n / (sum(n)),
         data = factor(correct, levels = c(0,1), labels = c("0", "1")),
         prediction = factor(pred, levels = c(0,1), labels = c("0", "1")))%>%
  ggplot(aes(x = prediction, y = data, fill = prop))+
  geom_tile(colour="black",size=0.5)+
  facet_grid(~model)+
  coord_fixed()+
  theme_few()+
  scale_fill_gradient(low = "#FDE1C4", high = "#40798C", limit = c(0,1), name="Proportion")
```


```{r}
data_binned <- data%>%
  filter(task == "combination")%>%
  group_by(subage, condition,familiar)%>%
  summarize(k = sum(correct, na.rm = T), n = n())%>%
  ungroup() %>%
  mutate(a = 1 + k,
         b = 1 + n - k,
         data_mean = (a-1)/(a+b-2),
         data_ci_lower  = qbeta(.025, a, b),
         data_ci_upper = qbeta(.975, a, b),
         subage = factor(subage)
         )%>%
  select(-a,-b,-n,-k)#%>%


model_binned <- model_predictions%>%
  select(-a, -g)%>%
  rename(model = b,
         condition = c,
         familiar = d,
         subid = e,
         pred = f)%>%
  left_join(data %>% select(condition,familiar,subid,subage))%>%
  filter(!is.na(subid), !is.na(subage))%>%
  mutate(subage = factor(subage))%>%
  group_by(model,subage, condition, familiar)%>%
  summarise(model_mean = mean(pred),
            model_ci_lower = hdi_lower(pred),
            model_ci_upper = hdi_upper(pred))

# flat_model_binned <- flat_model_predictions%>%
#   select(-a, -g)%>%
#   rename(model = b,
#          condition = c,
#          familiar = d,
#          subid = e,
#          pred = f)%>%
#   #left_join(data %>% select(condition,familiar,subid,subage))%>%
#   #filter(!is.na(subid), !is.na(subage))%>%
#   #mutate(subage = factor(subage))%>%
#   group_by(model, familiar)%>%
#   summarise(model_mean = mean(pred),
#             model_ci_lower = hdi_lower(pred),
#             model_ci_upper = hdi_upper(pred))

# global_model_binned <- global_model_predictions%>%
#   select(-a, -g)%>%
#   rename(model = b,
#          condition = c,
#          familiar = d,
#          age_month = e,
#          pred = f)%>%
#   mutate(subage = factor(ifelse(age_month < 1, "3", "4")))%>%
#   group_by(model, subage, condition, familiar)%>%
#   summarise(model_mean = mean(pred),
#             model_ci_lower = hdi_lower(pred),
#             model_ci_upper = hdi_upper(pred))


cor_plot <-  bind_rows(model_binned %>% left_join(data_binned)
                       #flat_model_binned %>% left_join(data_binned)%>%mutate(type = "RE_flat"),
                       #global_model_binned %>% left_join(data_binned)%>%mutate(type = "global")
                       )

ggplot(data = cor_plot,aes(x = model_mean, y = data_mean, col = subage)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = .5)+
  geom_errorbar(aes(ymin = data_ci_lower, ymax = data_ci_upper),width = 0,size = .5, alpha = .7)+
  geom_errorbarh(aes(xmin = model_ci_lower, xmax = model_ci_upper), height = 0,size = .5, alpha = .7)+
  geom_point(size = 1.5, stroke = 1, pch = 5)+
  coord_fixed()+
  facet_grid(~model)+
stat_cor(method = "pearson", label.x = 0.01, label.y = 0.99, aes(x = model_mean, y = data_mean, label = paste(..rr.label..)), inherit.aes = F, size = 3)+
  xlim(0,1)+ylim(0,1)+
  xlab("Model")+
  ylab("Data")+
  theme_few() + 
  scale_colour_ptol()

```


### Individual predictions

```{r}
idm <- model_predictions%>%
  select(-a, -g)%>%
  rename(model = b,
         condition = c,
         familiar = d,
         subid = e,
         pred = f)%>%
  filter(subid == 13028)

idd <- data%>%
  filter(subid == 13028 ,task == "combination")

idm %>%
  ggplot(aes(x = pred, y = familiar, fill = model))+
  geom_density_ridges(alpha = .5, scale = 3)+
  geom_point(data =idd, aes(x = correct, y = familiar), size = 3, stroke = 1, fill = "darkgreen",  col = "darkgreen", pch = 4)+
  facet_wrap(~condition, scales = "free_y")+
  scale_fill_ptol()+
  theme_few()

```

```{r}
idm <- model_predictions%>%
  select(-a, -g)%>%
  rename(model = b,
         condition = c,
         familiar = d,
         subid = e,
         pred = f)%>%
  filter(model == "combination", familiar == "lock")

idm %>%
  ggplot(aes(x = pred, y = familiar, fill = factor(chain)))+
  geom_density_ridges(alpha = .5)+
  #geom_point(data =idd, aes(x = correct, y = familiar), size = 3, stroke = 1, fill = "darkgreen",  col = "darkgreen", pch = 4)+
  facet_wrap(~subid, scales = "free_y")+
  scale_fill_ptol()+
  theme_few()

```
# Model parameters

## Production probability

```{r}
model%>%
  filter(c == "successful_production_probability")%>%
  rename(value = f)%>%
  ggplot(., aes(x = value, fill = factor(chain)))+
  geom_density(alpha = .5)+
  scale_fill_colorblind()+
  xlim(0,1)+
  theme_minimal()
```

## Speaker optimality

### overall intercept, slope and sigma

```{r}
model%>%
  filter(c == "speaker_optimality", 
         b != "parameters")%>%
  rename(parameter = b,
         value = f)%>%
  mutate(parameter = factor(parameter, levels = c("intercept", "slope", "sigma")))%>%
  ggplot(., aes(x = value, fill = factor(chain)))+
  geom_density(alpha = .5)+
  facet_grid(~parameter)+
  scale_fill_colorblind()+
  xlim(-4,4)+
  theme_minimal()
```


### by subject

```{r}
model%>%
  rename(type = b,
         parameter = c,
         subject = e, 
         speaker_optimality = f,)%>%
  filter(type != "sigma",
         parameter == "speaker_optimality",
         )%>%
  ggplot(., aes(x = speaker_optimality, fill = chain))+
  geom_density(alpha = .5)+
  facet_wrap(subject~., scales = "free_y")+
  scale_fill_colorblind()+
  theme_minimal()
```


## Semantic knowledge

### overall intercept, slope and sigma

```{r}
model%>%
  filter(c == "semantic_knowledge", 
         b != "parameters")%>%
  rename(parameter = b,
         value = f)%>%
  mutate(parameter = factor(parameter, levels = c("intercept", "slope", "sigma")))%>%
  ggplot(., aes(x = value, fill = factor(chain)))+
  geom_density(alpha = .5)+
  facet_grid(~parameter)+
  scale_fill_colorblind()+
  xlim(-4,4)+
  theme_minimal()
```

### by subject

```{r}
model%>%
  rename(parameter = c,
         familiar = d, 
         subject = e, 
         value = f)%>%
  filter(!is.na(familiar),
         parameter == "semantic_knowledge", 
         familiar == "lock")%>%
  ggplot(., aes(x = value, fill = factor(chain)))+
  geom_density(alpha = .5)+
  ggtitle("Semantic knowledge for 'lock'")+
  facet_wrap(subject~., scales = "free_y")+
  scale_fill_colorblind()+
  theme_minimal()
```

### by item

```{r}
model%>%
  rename(parameter = c,
         familiar = d, 
         subject = e, 
         value = f)%>%
  filter(!is.na(familiar),
         !is.na(value),
         !is.na(subject),
         parameter == "semantic_knowledge")%>%
  group_by(subject, familiar,chain)%>%
    summarise(mode = estimate_mode(value),
            lci = hdi_lower(value),
            uci = hdi_upper(value))%>%
  ggplot(., aes(x = factor(subject), y= mode, col = chain))+
  geom_pointrange(aes(ymin = lci, ymax = uci), position = position_dodge(width = .1), pch = 4)+
  scale_color_colorblind()+
  facet_grid(familiar~.)+
  theme_few()
```

## Prior sensitivity

### overall intercept, slope and sigma

```{r}
model%>%
  filter(c == "prior", 
         b != "parameters")%>%
  rename(parameter = b,
         value = f)%>%
  mutate(parameter = factor(parameter, levels = c("intercept", "slope", "sigma")))%>%
  ggplot(., aes(x = value, fill = factor(chain)))+
  geom_density(alpha = .5)+
  facet_grid(~parameter)+
  scale_fill_colorblind()+
  xlim(-4,4)+
  theme_minimal()
```

### by subject

```{r}
model%>%
  rename(parameter = c, 
         familiar = d, 
         subject = e, 
         value = f)%>%
  filter(!is.na(subject),
         parameter == "prior")%>%
  ggplot(., aes(x = value, fill = factor(chain)))+
  geom_density(alpha = .5)+
  facet_wrap(subject~., scales = "free_y")+
  scale_fill_colorblind()+
  xlim(0,1)+
  theme_minimal()

```

