---
title: "Spin-within"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(ggthemes)
library(jsonlite)
library(readxl)
library(tidyboot)
library(GGally)
library(ggpubr)


```

# Comprehension

```{r}

# get data:

# rsync -zaP manuelb@ccp-odc.eva.mpg.de:/srv/ccp-odc/manuel_bohn/spin-within/data/  ~/Work/Local/Spin-within/raw_data/

files <- dir("~/Work/Local/Spin-within/raw_data", pattern = ".json")

raw_data1 <- tibble()
for (f in files) {
  jf <- paste("~/Work/Local/Spin-within/raw_data/",f,sep="")
  jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
  date <- str_sub(jf,47,str_length(jf)-11)
  id <- as_tibble(jd$data$data) %>% mutate(test_date = date,
                                              trial = as.character(trial))
  raw_data1 <- bind_rows(raw_data1, id)
}

hand_code_data <- read_csv("../../../../Cloud/spin-within/11890_combination_data.csv")%>%
  mutate(status = "keep",
         subid = as.character(subid),
         subage = as.character(subage),
         trial = as.character(trial),
         test_date = as.character(test_date))%>%
  select(-age, -age_month, -`...5`, -status)

raw_data <- bind_rows(
  raw_data1,
  hand_code_data
)

invalid_trials <- read_excel("../../../../Cloud/spin-within/invalid_trials.xlsx")%>%
  mutate(subid = as.character(subid),
         subage = as.character(subage),
         trial = as.character(trial))%>%
  right_join(raw_data)%>%
  filter(valid == "no")%>%
  mutate(correct = NA)%>%
  select(-valid)

valid_data <- raw_data %>%
  left_join(read_excel("../../../../Cloud/spin-within/invalid_trials.xlsx")%>%
  mutate(subid = as.character(subid),
         subage = as.character(subage),
         trial = as.character(trial)))%>%
  filter(is.na(valid))%>%
  select(-valid)%>%
  bind_rows(invalid_trials)

log_id <- read_excel("../../../../Cloud/spin-within/spin-within_subject_list.xlsx")%>%
  mutate(birthday = as.Date(birthday, format = "%d.%m.%Y"),
         test_day_1 = as.Date(test_day_1, format = "%d.%m.%Y"),
         test_day_2 = as.Date(test_day_2, format = "%d.%m.%Y"),
         age_num = as.numeric(difftime(test_day_1, birthday, units = "days"))/365.25,
         age_month = round(lubridate::time_length(difftime(test_day_1, birthday),"month"))/12)%>%
  rename(subid = ID,
         subage = age,
         age = age_num)%>%
  select(subid, subage,age,age_month, status)

log_prod <- read_excel("../../../../Cloud/spin-within/vocab_codingsheet.xlsx")%>%
  filter(task == "production")%>%
  #select(-`...5`)%>%
  rename(subid = ID,
         familiar = object,
         correct = performance)%>%
 #filter(correct != "NA")%>%
  mutate(subid = as.character(subid), 
         correct = as.numeric(correct))

# add filtering of invalid trials

data <-  valid_data%>%
  mutate(subage = ifelse(subage == "4 ", "4", subage),
         familiar = ifelse(task == "comprehension", target, familiar), 
         subage = ifelse(subid == "79783", "4", subage),
         subid = ifelse(subage == "89475", "89475",subid),
         subid = ifelse(subid == "41433", "41423",subid),
         subage = ifelse(subid == "89475","3",subage ))%>%
  left_join(log_id)%>%
  bind_rows(log_prod%>%left_join(log_id))%>%
  filter(status == "keep", 
         !grepl("train",trial))%>%
  select(-target)%>%
  mutate(age = age - min(age),
         condition = ifelse(task == "combination", ifelse(
           familiar == "rasp" | familiar == "hanger" | familiar == "mic" | familiar == "pincer", "incongruent",
           ifelse(familiar == "lock" | familiar == "opener" | familiar == "bread" | familiar == "tweezers", "congruent", condition)
         ), condition))

write_csv(data,"../data/merged_data.csv")

# 
# # Für Louisa ab hier: 
data <- read_csv("../data/merged_data.csv")%>%
  arrange(test_date)%>%
  mutate(subage = factor(subage))
# 
# Das folgende kannst ignorieren, Louisa. 
ex_id <- data%>%
  group_by(subid)%>%
  summarise(me = sum(task == "mutual_exclusivity"),
            novelty = sum(task == "novelty"),
            combination = sum(task == "combination"),
            comp = sum(task == "comprehension"),
            prod = sum(task == "production"))%>%
  filter(prod < 16)%>%
  pull(subid)
# # 
mdata <- data%>%
  filter(!subid %in% ex_id)%>%
  mutate(age = age - min(age),
         age_month = age_month - min(age_month))
# # 
write(toJSON(data), file = "../data//merged_data.json")

```

# Sample
```{r}
data%>%
  group_by(subid)%>%
  summarise(me = sum(task == "mutual_exclusivity"),
            novelty = sum(task == "novelty"),
            combination = sum(task == "combination"),
            comp = sum(task == "comprehension"),
            prod = sum(task == "production"))

```
# Single tasks

```{r}
p1 <- data %>%
  filter(task != "combination")%>%
  group_by(subage,task, subid) %>%
  filter(!grepl("train",trial)) %>%
  summarise(mean = mean(correct, na.rm = T))

p2 <- p1 %>%
  group_by(subage,task) %>%
  tidyboot_mean(column = mean, na.rm = T)%>%
  mutate(chance = ifelse(task == "mutual_exclusivity" | task == "novelty", 1/2, NA))

ggplot()+
  geom_hline(data = p2, aes(yintercept =chance), lty = 2, alpha = .5)+
  #geom_smooth(data = p1, aes(x = subage, y = mean), method = "lm", col = "black", size = 1)+
  geom_jitter(data = p1, aes(x = subage, y = mean), alpha = .5, width = .05, height = .01)+
  geom_pointrange(data = p2, aes(x = subage, y = mean, ymin = ci_lower, ymax = ci_upper, col = subage), position = position_dodge(width = .5))+
  facet_grid(~task)+
  labs(x = "Age Group", y = "Proportion Correct") +
  scale_color_ptol(name = "Age") +
  ylim(-0.05, 1.05)+
  theme_few()
```
```{r}
data %>%
  filter(task != "combination")%>%
  group_by(task, subid,age) %>%
  filter(!grepl("train",trial)) %>%
  summarise(mean = mean(correct, na.rm = T))%>%
  ggplot(aes(x = age, y = mean))+
  geom_hline(data = p2, aes(yintercept =chance), lty = 2, alpha = .5)+
  geom_smooth(method = "lm", col = "black", size = 1)+
  geom_jitter(alpha = .5, width = .05, height = .01)+
  facet_grid(~task)+
  labs(x = "Age", y = "Proportion Correct") +
  ylim(-0.05, 1.05)+
  theme_few()
  
```


# Correlations between tasks requiring semantic knowledge 

```{r}
cor <- data %>% 
  filter(task == "mutual_exclusivity" | task == "comprehension" | task == "production")%>%
  group_by(subid,subage, task)%>%
  summarise(mean = mean(correct, na.rm = T))%>%
  pivot_wider(names_from = "task", values_from = "mean")%>%
  ungroup()

ggpairs(cor, columns =3:5)+
  theme_few()+
  scale_colour_ptol()
```

# combination

```{r}
pc <- data %>%
  filter(task == "combination")%>%
  filter(!grepl("train",trial)) %>%
  group_by(subage,task,familiar,condition) %>%
  tidyboot_mean(column = correct, na.rm = T)


ggplot()+
  #geom_hline(yintercept = 0.5, lty = 2, alpha = .5)+
  #geom_smooth(data = p1, aes(x = subage, y = mean), method = "lm", col = "black", size = 1)+
  #geom_jitter(data = pc, aes(x = subage, y = mean), alpha = .5, width = .05, height = .01)+
  geom_pointrange(data = pc, aes(x = familiar, y = mean, ymin = ci_lower, ymax = ci_upper, col = subage), position = position_dodge(width = .9))+
  facet_grid(~condition, scales = "free_x")+
  labs(x = "Age Group", y = "Proportion unfamiliar object chosen") +
  scale_color_colorblind(name = "Condition") +
  ylim(-0.05, 1.05)+
  theme_few()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
data%>%
  filter(task == "mutual_exclusivity" | task == "combination")%>%
  group_by(task,familiar)%>%
  summarise(correct = mean(correct, na.rm = T))%>%
  pivot_wider(names_from = "task", values_from = "correct")%>%
  left_join(data%>%filter(task =="combination")%>%select(familiar,condition)%>%distinct())%>%
  ggplot(., aes(x = mutual_exclusivity, y = combination))+
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = .5)+
  geom_point(aes(col = familiar), alpha = .75)+
  stat_cor()+
  theme_minimal()+
  xlim(0,1)+ ylim(0,1)+
  facet_grid(~condition)
```

```{r}
data%>%
  filter(task == "mutual_exclusivity" | task == "combination")%>%
  group_by(subage,task,familiar)%>%
  summarise(correct = mean(correct, na.rm = T))%>%
  left_join(data%>%filter(task =="combination")%>%select(familiar,condition)%>%distinct())%>%
  ggplot(., aes(x = task, y = correct, col = familiar))+
  geom_line(aes(group = familiar))+
  geom_point(alpha = .75)+
  theme_few()+
  ylim(0,1)+
  facet_grid(subage~condition)
```

