---
title: "Spin-within model comparison"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(ggthemes)
library(jsonlite)
library(readxl)
library(tidyboot)
library(coda)
library(data.table)
library(matrixStats)

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}

```

# Output

```{r}
model_comp <-  bind_rows(
  fread("../model/output/spin-within_model_comparison-chain1.csv"),
  fread("../model/output/spin-within_model_comparison-chain2.csv"),
  fread("../model/output/spin-within_model_comparison-chain3.csv"),
  fread("../model/output/spin-within_model_comparison-chain4.csv"),
  fread("../model/output/spin-within_model_comparison-chain5.csv"),
  fread("../model/output/spin-within_model_comparison-chain6.csv"),
  fread("../model/output/spin-within_model_comparison-chain7.csv"),
  fread("../model/output/spin-within_model_comparison-chain8.csv"),
  fread("../model/output/spin-within_model_comparison-chain9.csv"),
  fread("../model/output/spin-within_model_comparison-chain10.csv")
)

saveRDS(model_comp, "../model/output/model_comparison.rds")

model_comp <- readRDS("../model/output/model_comparison.rds")
```

# Model comparison

## by chain

```{r}
model_comp %>%
  group_by(model,chain)%>%
  summarise(margllh = logSumExp(loglike))%>%
  pivot_wider(names_from = model, values_from = margllh)
```

## overall (log Bayes Factor)

```{r}
model_comp %>%
  group_by(model)%>%
  summarise(margllh = logSumExp(loglike))%>%
  pivot_wider(names_from = model, values_from = margllh)%>%
  summarise(bf_comb_flat = combination - flatPrior, 
            bf_comb_prior = combination - priorOnly)
```

## Plot for log-likelihood

### Distribution

```{r}
model_comp%>%
  ggplot(aes(x= loglike, fill = model))+
  facet_wrap(~chain, scales = "free")+
  geom_density(alpha = .5)+
  scale_fill_colorblind()+
  theme_minimal()
```

### Expected value

```{r}
model_comp %>%
  group_by(model)%>%
  summarise(margllh = logSumExp(loglike))%>%
  ggplot(aes(x = model, y = margllh, col = model))+
  geom_segment( aes(x=model, xend=model, y=margllh, yend=-400), col = "black", size = 1)+
  geom_point(size = 7)+
  theme_few()+ 
  xlab("")+
  ylab("Log-likelihood")+
  theme(axis.text.x=element_text(angle = 45, vjust = 1, hjust = 1))+
  guides()+
  scale_color_manual(name = "Model",
                     labels=c("Integration","No Common Ground","No Speaker Informativeness"),
                     
                    values= c("#6a994e","#a71e34","#da1e37","#0582ca","#003554"))+
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
```

```{r}
ggsave("../graphs/like_plot_full.png", width = 5, height = 3, scale = 1.5)
```

# Individual BFs

```{r}
model_comp_id <-  bind_rows(
  fread("../model/output/spin-within_model_comparison_individual-chain1.csv")#,
  # fread("../model/output/spin-within_model_comparison_individual-chain2.csv"),
  # fread("../model/output/spin-within_model_comparison_individual-chain3.csv"),
  # fread("../model/output/spin-within_model_comparison_individual-chain4.csv"),
  # fread("../model/output/spin-within_model_comparison_individual-chain5.csv"),
  # fread("../model/output/spin-within_model_comparison_individual-chain6.csv"),
  # fread("../model/output/spin-within_model_comparison_individual-chain7.csv"),
  # fread("../model/output/spin-within_model_comparison_individual-chain8.csv"),
  # fread("../model/output/spin-within_model_comparison_individual-chain9.csv"),
  # fread("../model/output/spin-within_model_comparison_individual-chain10.csv")
)

#saveRDS(fread("../model/output/spin-within_model_comparison_individual-chain1.csv"), "../model/output/model_comparison_id_1.rds")

# For MH to get an idea of what the output looks like and to reproduce the logSumExp problem
# These are samples from a single chain, but they show the general issue
model_comp_id <- readRDS("../model/output/model_comparison_id_1.rds")
```

```{r}
range(model_comp_id$loglike)
```

## overall

```{r}
model_comp_id %>%
  filter(scope == "global")%>%
  group_by(model,chain)%>%
  summarise(margllh = logSumExp(loglike))%>%
  pivot_wider(names_from = model, values_from = margllh)
```

## by chain

```{r}
model_comp_id %>%
  filter(scope == "id")%>%
  group_by(model,id,chain)%>%
  summarise(margllh = logSumExp(loglike))%>%
  pivot_wider(names_from = model, values_from = margllh)
```

```{r}
model_comp_id %>%
  filter(scope == "id")%>%
  group_by(model,id,chain)%>%
  summarise(margllh = logSumExp(loglike))%>%
  pivot_wider(names_from = model, values_from = margllh)%>%
  group_by(id)%>%
  summarise(comb_min = min(combination), 
            comb_max = max(combination),
            flat_min = min(flatPrior), 
            flat_max = max(flatPrior),
            prior_min = min(priorOnly), 
            prior_max = max(priorOnly))

model_comp_id %>%
  filter(scope == "id")%>%
  group_by(model,id,chain)%>%
  summarise(max_loglike = max(loglike),
            min_loglike = min(loglike))
```

## overall (log Bayes Factor)

```{r}
id_bf <- model_comp_id %>%
  filter(scope == "id")%>%
  group_by(model, id)%>%
  summarise(margllh = logSumExp(loglike))%>%
  pivot_wider(names_from = model, values_from = margllh)%>%
  group_by(id)%>%
  summarise(bf_comb_flat = combination - flatPrior, 
            bf_comb_prior = combination - priorOnly)%>%
  pivot_longer(cols = c(bf_comb_flat, bf_comb_prior), names_to = "Comparison", values_to = "log_BF")
```

```{r}
id_bf%>%
  group_by(Comparison)%>%
  summarise(prop_pos_BF = sum(log_BF > 0)/60)
```

```{r}
id_bf%>%
  ggplot(aes(x = log_BF, fill = Comparison))+
  geom_vline(xintercept = c(0,log(3),log(10)), lty = 2, alpha = .75)+
  geom_density(alpha = .5)+
  geom_point(aes(y = 0, col = Comparison), pch = "I", size = 5)+
  theme_minimal()+
  scale_fill_colorblind()+
  scale_color_colorblind()
```



