---
title: "Spin-within model output"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(ggthemes)
library(jsonlite)
library(readxl)
library(tidyboot)
#library(GGally)
library(coda)
library(data.table)


estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}

```

# Comprehension

```{r}
data <- read_csv("../data/merged_data.csv")

data_agg <- data %>%
  rename(subject = subid)%>%
  mutate(familiar = ifelse(task == "novelty", "novelty", familiar))%>%
  filter(task != "combination")%>%
  group_by(subject, familiar)%>%
  summarise(mean = mean(correct))
```

# Model Output

```{r}
model <-  bind_rows(
  fread("../model/output/spin-within_model-20000_burn100000_lag9_chain1.csv")%>%mutate(chain = "1"),
  fread("../model/output/spin-within_model-20000_burn100000_lag9_chain2.csv")%>%mutate(chain = "2"),
  fread("../model/output/spin-within_model-20000_burn100000_lag9_chain3.csv")%>%mutate(chain = "3"),
  fread("../model/output/spin-within_model-20000_burn100000_lag9_chain4.csv")%>%mutate(chain = "4"),
  fread("../model/output/spin-within_model-20000_burn100000_lag9_chain5.csv")%>%mutate(chain = "5")
)
```

## Sigmas

```{r}
model%>%
  filter(b == "sigma")%>%
  rename(parameter = c,
         value = f)%>%
  ggplot(., aes(x = value, fill = chain))+
  geom_density(alpha = .5)+
  facet_grid(~parameter)+
  scale_fill_colorblind()+
  xlim(0,3)+
  theme_minimal()
  
```

# Production probability

```{r}
model%>%
  filter(c == "successful_production_probability")%>%
  rename(value = f)%>%
  ggplot(., aes(x = value, fill = chain))+
  geom_density(alpha = .5)+
  scale_fill_colorblind()+
  xlim(0,1)+
  theme_minimal()
```

## Speaker optimality

```{r}
model%>%
  rename(type = b,
         parameter = c,
         subject = e, 
         speaker_optimality = f)%>%
  filter(type != "sigma",
         parameter == "speaker_optimality")%>%
  ggplot(., aes(x = speaker_optimality, fill = chain))+
  geom_density(alpha = .5)+
  facet_grid(subject~., scales = "free_y")+
  scale_fill_colorblind()+
  theme_minimal()
```


## Semantic knowledge

```{r}
model%>%
  rename(parameter = c,
         familiar = d, 
         subject = e, 
         value = f)%>%
  filter(!is.na(familiar),
         parameter == "semantic_knowledge", 
         familiar == "sieve")%>%
  ggplot(., aes(x = value, fill = chain))+
  geom_density(alpha = .5)+
  facet_grid(subject~., scales = "free_y")+
  scale_fill_colorblind()+
  theme_minimal()
```



```{r}
model%>%
  rename(parameter = c,
         familiar = d, 
         subject = e, 
         value = f)%>%
  filter(!is.na(familiar),
         parameter == "semantic_knowledge")%>%
  group_by(subject, familiar,chain)%>%
    summarise(mode = estimate_mode(value),
            lci = hdi_lower(value),
            uci = hdi_upper(value))%>%
  ggplot(., aes(x = familiar, y= mode, col = chain))+
  geom_pointrange(aes(ymin = lci, ymax = uci), position = position_dodge(width = .5), pch = 4)+
  scale_color_colorblind()+
  facet_grid(~subject)+
  coord_flip()+
  theme_few()
```

## Prios sensitivity
```{r}
model%>%
  rename(parameter = c, 
         familiar = d, 
         subject = e, 
         value = f)%>%
  filter(!is.na(subject),
         parameter == "prior")%>%
  ggplot(., aes(x = value, fill = chain))+
  geom_density(alpha = .5)+
  facet_grid(subject~.)+
  scale_fill_colorblind()+
  xlim(0,1)+
  theme_minimal()

```

